services:
  watsonxai-endpoint:
    image: fenglixa/watsonxai-endpoint:1.1
    container_name: watsonxai-endpoint
    env_file: .env
    environment:
      - WATSONX_IAM_APIKEY=${WATSONX_IAM_APIKEY}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - WATSONX_REGION=${WATSONX_REGION}
    volumes:
      - ./:/app
    ports:
      - "8081:8000"
    restart: always
